<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ActitoSdk.Push.UI.iOS.Binding</RootNamespace>

        <!--
          Enable trim analyzers for class libraries.
          To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
        -->
        <IsTrimmable>true</IsTrimmable>
    </PropertyGroup>

    <ItemGroup>
        <ObjcBindingApiDefinition Include="ApiDefinitions.cs"/>
        <ObjcBindingCoreSource Include="StructsAndEnums.cs"/>
    </ItemGroup>

    <ItemGroup>
        <XcodeProject Include="../Actito.Push.UI.iOS.Binding.Bridge/ActitoPushUIBinding.xcodeproj">
            <SchemeName>ActitoPushUIBinding</SchemeName>
            <!-- Metadata applicable to @(NativeReference) will be used if set, otherwise the following defaults will be used:
            <Kind>Framework</Kind>
            <SmartLink>true</SmartLink>
            -->
        </XcodeProject>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Actito.iOS.Binding\Actito.iOS.Binding.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <NativeReference Include="libs/ActitoPushUIKit.xcframework">
            <Kind>Framework</Kind>
            <ForceLoad>True</ForceLoad>
            <SmartLink>False</SmartLink>
            <Frameworks>Foundation UIKit</Frameworks>
            <Visible>True</Visible>
        </NativeReference>
    </ItemGroup>
</Project>
