<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ActitoSdk.Scannables</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Actito.Scannables.Core\Actito.Scannables.Core.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('android'))">
        <ProjectReference Include="..\Actito.Scannables.Android\Actito.Scannables.Android.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('ios'))">
        <ProjectReference Include="..\Actito.Scannables.iOS\Actito.Scannables.iOS.csproj"/>
    </ItemGroup>
</Project>
