<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ActitoSdk.InAppMessaging</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Actito.InAppMessaging.Core\Actito.InAppMessaging.Core.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('android'))">
        <ProjectReference Include="..\Actito.InAppMessaging.Android\Actito.InAppMessaging.Android.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('ios'))">
        <ProjectReference Include="..\Actito.InAppMessaging.iOS\Actito.InAppMessaging.iOS.csproj"/>
    </ItemGroup>
</Project>
