<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ActitoSdk.Loyalty.iOS.Binding</RootNamespace>

        <!--
          Enable trim analyzers for class libraries.
          To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
        -->
        <IsTrimmable>true</IsTrimmable>
    </PropertyGroup>

    <ItemGroup>
        <ObjcBindingApiDefinition Include="ApiDefinitions.cs"/>
        <ObjcBindingCoreSource Include="StructsAndEnums.cs"/>
    </ItemGroup>

    <ItemGroup>
        <XcodeProject Include="../Actito.Loyalty.iOS.Binding.Bridge/ActitoLoyaltyBinding.xcodeproj">
            <SchemeName>ActitoLoyaltyBinding</SchemeName>
            <!-- Metadata applicable to @(NativeReference) will be used if set, otherwise the following defaults will be used:
            <Kind>Framework</Kind>
            <SmartLink>true</SmartLink>
            -->
        </XcodeProject>
    </ItemGroup>

    <ItemGroup>
        <NativeReference Include="libs/ActitoLoyaltyKit.xcframework">
            <Kind>Framework</Kind>
            <ForceLoad>True</ForceLoad>
            <SmartLink>False</SmartLink>
            <Frameworks>Foundation UIKit PassKit</Frameworks>
            <Visible>True</Visible>
        </NativeReference>
    </ItemGroup>
</Project>
