<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ActitoSdk.Loyalty.Android.Binding</RootNamespace>

        <!--
          Enable trim analyzers for Android class libraries.
          To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
        -->
        <IsTrimmable>true</IsTrimmable>

        <NativeLibraryVersion>5.0.0-beta.2</NativeLibraryVersion>
        <NativeLibraryMavenRepository>Central</NativeLibraryMavenRepository>
    </PropertyGroup>

    <ItemGroup>
        <AndroidMavenLibrary
                Include="com.actito:actito-loyalty"
                Version="$(NativeLibraryVersion)"
                VerifyDependencies="false"
                Bind="true"
                Repository="$(NativeLibraryMavenRepository)"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Actito.Android.Binding\Actito.Android.Binding.csproj"/>
    </ItemGroup>
</Project>
