<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ActitoSdk.Loyalty.iOS</RootNamespace>

        <!--
          Enable trim analyzers for class libraries.
          To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
        -->
        <IsTrimmable>true</IsTrimmable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Actito.iOS\Actito.iOS.csproj"/>

        <ProjectReference Include="..\Actito.Loyalty.Core\Actito.Loyalty.Core.csproj"/>
        <ProjectReference Include="..\Actito.Loyalty.iOS.Binding\Actito.Loyalty.iOS.Binding.csproj"/>
    </ItemGroup>
</Project>
