<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ActitoSdk.Assets.Android</RootNamespace>
        
        <!--
          Enable trim analyzers for Android class libraries.
          To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
        -->
        <IsTrimmable>true</IsTrimmable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Actito.Android\Actito.Android.csproj"/>

        <ProjectReference Include="..\Actito.Assets.Core\Actito.Assets.Core.csproj"/>
        <ProjectReference Include="..\Actito.Assets.Android.Binding\Actito.Assets.Android.Binding.csproj"/>
    </ItemGroup>
</Project>
