<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ActitoSdk.UserInbox</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Actito.UserInbox.Core\Actito.UserInbox.Core.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('android'))">
        <ProjectReference Include="..\Actito.UserInbox.Android\Actito.UserInbox.Android.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('ios'))">
        <ProjectReference Include="..\Actito.UserInbox.iOS\Actito.UserInbox.iOS.csproj"/>
    </ItemGroup>
</Project>
